chocolatey/ChocolateyGUI

Source/ChocolateyGui/Services/PackageServices/ODataPackageService.cs
- Made use of the GetFeed method, rather than creating new Feed directly
- This ensures that all properties, like ignoring missing properties,
are set
=> Corrected addition of new Source

ABOUT.md, Source/ChocolateyGui.sln, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/IoC/AutoFacConfiguration.cs, Source/ChocolateyGui/Providers/IVersionNumberProvider.cs, Source/ChocolateyGui/Providers/VersionNumberProvider.cs, Source/ChocolateyGui/Resources/Controls.xaml, Source/ChocolateyGui/Utilities/ResourceReader.cs, Source/ChocolateyGui/ViewModels/Windows/MainWindowViewModel.cs, Source/ChocolateyGui/Views/Windows/MainWindow.xaml, Source/ChocolateyGui/Views/Windows/MainWindow.xaml.cs, docs/legal/CREDITS.md
- Added ResourceReader to parse contents of selected markdown files
which are included in the repository
- Updated View and ViewModel to render these files into the UI in the
form of an About box with multiple tabs
- Using information that was made available here:
https://github.com/theunrepentantgeek/Markdown.XAML/issues/5
- Added Window Command Binding for handling Hyperlink Clicks which are
rendered from markdown content
=> Adding About, Credits and Release Notes Tab

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/IoC/AutoFacConfiguration.cs, Source/ChocolateyGui/Services/IPersistenceService.cs, Source/ChocolateyGui/Services/PersistenceService.cs, Source/ChocolateyGui/ViewModels/Controls/ILocalSourceControlViewModel.cs, Source/ChocolateyGui/ViewModels/Controls/LocalSourceControlViewModel.cs, Source/ChocolateyGui/Views/Controls/LocalSourceControl.xaml
- Using a simple PersistenceService, i.e. Open/Save Dialog
- Provide option to export the current list of installed packages to a packages.config file
=> Ability to Export currently installed packages

README.md
Re: this thread https://twitter.com/gep13/status/628447363649118208
=> Indicate usage of ZenHub

Source/ChocolateyGui/ViewModels/Controls/LocalSourceControlViewModel.cs
After "update all" there will be a "refresh packages" to show the
updated packages correctly (e.g. updated version information) and "Show
Only Packages with Updates" will be unchecked
=> (GH-288) Improved GUI behavior after "update all"

Source/ChocolateyGui/App.xaml, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Commands/CommandExecutionManager.cs, Source/ChocolateyGui/Controls/Dialogs/ChocolateyDialog.xaml, Source/ChocolateyGui/Controls/Dialogs/ChocolateyDialog.xaml.cs, Source/ChocolateyGui/Resources/ControlStyles/SourceList.xaml, Source/ChocolateyGui/Resources/Controls.xaml, Source/ChocolateyGui/Resources/Theme.xaml, Source/ChocolateyGui/Services/PackageServices/BasePackageService.cs, Source/ChocolateyGui/Services/PackageServices/ChocolateyPackageService.cs, Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs, Source/ChocolateyGui/Views/Controls/LocalSourceControl.xaml, Source/ChocolateyGui/Views/Controls/PackageControl.xaml, Source/ChocolateyGui/Views/Controls/RemoteSourceControl.xaml, Source/ChocolateyGui/Views/Controls/SourcesControl.xaml, Source/ChocolateyGui/Views/Windows/MainWindow.xaml, Source/ChocolateyGui/app.config
Applies a new chocolatey-inspired theme, as well as consoidated a number of styles brushes and fixing a few misc errors.
cc: @ferventcoder @gep13
=> Re-Theme and Fixes

ChocolateyPackage/chocolateyInstall.ps1
Fix install error introduced with #361
=> Fix chocolateyInstall

ChocolateyPackage/chocolateyUninstall.ps1
Remove deprecated functions from chocoUninstall and replace aliases with full commands
=> Remove deprecated functions

ChocolateyPackage/chocolateyInstall.ps1
Delete MSI after installation and add software name
=> Improve chocolateyInstall

Source/ChocolateyGui/Bootstrapper.cs, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Startup/Internationalization.cs, Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs
/cc @mwallner 
Certain things like date times will still have to be manually tweaked, but this should cover the issue in 90% of cases. This *should* fix resxs. Still need to test more.
Related; #381
=> Fix xaml culture

docs/input/docs/localization-howto.md
there should be a localization-howto.md somewhere in docs
minimum requirements:
=> (GH-397) ChocolateyGUI Globalisation HowTo

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Properties/Resources.sv.resx
I made a mistake in #400, so I restart with this new PR for the Swedish translation.
I have taken into account the review comments from the old PR.  
#396
=> (GH-396) Added Swedish translation

docs/input/credits.md
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)
=> Correct name Christiaan

Source/ChocolateyGui/Properties/Resources.de.resx, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Properties/Resources.sv.resx
added missing German resource-strings using 'ResxTranslator 2.2'
=> GH-413 Add/Update missing German translation

Source/ChocolateyGui.Shared/ChocolateyGui.Shared.csproj, Source/ChocolateyGui.Shared/Hacks.cs, Source/ChocolateyGui.Subprocess/ChocolateyService.cs
=> (GH-436) Remove hacks for accessing chocolatey internals.

Source/ChocolateyGui.Subprocess/ChocolateyService.cs
Switch to implentation of outdated that mirrors chocolatey.
=> (GH-445) Fix outdated check

Source/ChocolateyGui.Shared/ChocolateyGui.Shared.csproj, Source/ChocolateyGui.Shared/Models/ChocolateySource.cs, Source/ChocolateyGui.Shared/packages.config, Source/ChocolateyGui.Subprocess/ChocolateyGui.Subprocess.csproj, Source/ChocolateyGui.Subprocess/ChocolateyService.cs, Source/ChocolateyGui.Subprocess/packages.config, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.de.resx, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Properties/Resources.sv.resx, Source/ChocolateyGui/Views/SettingsView.xaml, Source/ChocolateyGui/packages.config
Related to #432 
Closes #455 
This includes some changes that will only work with Chocolatey v0.10.8.
=> (GH-455)(GH-432) Sources updates / Chocolatey 0.10.8 updates

Source/ChocolateyGui/Properties/Resources.de.resx
small fixes for the German translation
=> GH-471 Fixes in German translation

Source/ChocolateyGui/Views/ShellView.xaml.cs
=> (GH-275) Added persistence of window size and position

README.md, nuspec/chocolatey/ChocolateyGUI.nuspec
=> (GH-427) Clarified OS support

Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs
@RichiCoder1 okay, so this feels sort of clunky, but...
Thoughts?
=> GH480: Persist current package details

Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.de.resx, Source/ChocolateyGui/Properties/Resources.nb.resx, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Properties/Resources.sv.resx, Source/ChocolateyGui/Views/LocalSourceView.xaml
=> make tooltips localizable and add german translation

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Controls/InternetImage.xaml.cs, Source/ChocolateyGui/packages.config
=> (GH-490) Switch SVG rendering from Cef to Magick.Net

Source/ChocolateyGui/Properties/Resources.sv.resx
Add missing tool tips from #486 and update some other translations.
=> Update Swedish translation

Source/ChocolateyGui/Properties/Resources.ru.resx
Hi, I found your project on github, I know , that your project is one of the firsts successful projects on Kikstarter, so I decided to add russian localization for your project.
=> Add russian localization

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Resources/Controls.xaml, Source/ChocolateyGui/Utilities/DataGridCustomSortBehavior.cs, Source/ChocolateyGui/Utilities/IDataGridColumnComparer.cs, Source/ChocolateyGui/Utilities/PackageAuthorsComparer.cs, Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs, Source/ChocolateyGui/Views/LocalSourceView.xaml, Source/ChocolateyGui/Views/RemoteSourceView.xaml
After implementing the tile view for the remote source it's more consequent to do this for the local package view too.
Changes
- Same tile view for local view
- Fix DataGrid sorting for Title and Authors
Relates to #517
=> Local Package Tile View Implementation

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Views/LocalSourceView.xaml, Source/ChocolateyGui/Views/RemoteSourceView.xaml, Source/ChocolateyGui/Views/SettingsView.xaml
- These will need to be filled in through Transifex for other languages
Fixes #523
=> (GH-523) Added new/missing translations

Source/ChocolateyGui/Models/AppConfiguration.cs, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Services/ConfigService.cs, Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs, Source/ChocolateyGui/ViewModels/RemoteSourceViewModel.cs, Source/ChocolateyGui/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui/Views/SettingsView.xaml
- Left the list views as the default for starting application
- Choice is persisted and set on next start of the application
@ferventcoder @mwallner @RichiCoder1 @pascalberger @punker76 Thoughts on the following:
=> (GH-524) Added ability to default to Tile View

Source/ChocolateyGui/Models/AppConfiguration.cs, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/ViewModels/RemoteSourceViewModel.cs, Source/ChocolateyGui/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui/Views/RemoteSourceView.xaml, Source/ChocolateyGui/Views/SettingsView.xaml
Related to #527 
Added checkbox in settings to disable/enable search with delay, by default searching with delay is disabled.
Added search button that is active even if search with delay is enabled.
=> GH527: Added search on enter.

Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Views/PackageView.xaml
=> GH530: Moved version to the left in PackageView.

Source/ChocolateyGui/Services/ChocolateyService.cs
No Prerelease were shown in ChocolateyGui package list.
=> Fix Setting Include Prerelease

Source/ChocolateyGui/Models/ChocolateySource.cs, Source/ChocolateyGui/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui/Views/SettingsView.xaml
* Changed `SelectedItem` to `CurrentItem`
`SelectedItem` is not getting updated after change to any source, I'm not sure why.
* Added `DraftSource` to prevent updating `SelectedSource` if save button was not clicked.
* Disabled multi select.
=> (GH-620) Fix showing selected source after editing source.

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/packages.config
Related to #584 #578 
Update to the latest version fixes this issue.
=> (GH-584, GH-578) Update Markdig.Wpf.

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Models/AppConfiguration.cs, Source/ChocolateyGui/Models/ChocolateyAggregatedSources.cs, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Resources/Controls.xaml, Source/ChocolateyGui/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui/ViewModels/SourceSeparatorViewModel.cs, Source/ChocolateyGui/ViewModels/SourcesListBoxItemStyleSelector.cs, Source/ChocolateyGui/ViewModels/SourcesViewModel.cs, Source/ChocolateyGui/Views/SettingsView.xaml, Source/ChocolateyGui/Views/SourcesView.xaml
This adds a setting option to show/hide an additional/virtual source that aggregates all sources.
(this aims to replace GH-591)
=> (GH-588) Add option to show aggregated source view

Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/Models/ChocolateySource.cs, Source/ChocolateyGui/Properties/Resources.Designer.cs, Source/ChocolateyGui/Properties/Resources.resx, Source/ChocolateyGui/Providers/NugetEncryptionUtility.cs, Source/ChocolateyGui/Services/ChocolateyService.cs, Source/ChocolateyGui/Services/IChocolateyService.cs, Source/ChocolateyGui/Startup/ChocolateyGuiModule.cs, Source/ChocolateyGui/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui/Views/SettingsView.xaml
Don't allow direct viewing of Source Password (as this is encrypted and meaningless to end user)
Use ShowLoginAsync method in Mahapps to add/edit user and password
=> (GH-665) Modifications to Sources Settings screen

docs/input/docs/localization-howto.md
=> (doc) Fix typo

recipe.cake
Disable generation of build script tasks documentation
=> (build) Disable documentation of build script tasks

nuspec/chocolatey/chocolateyInstall.ps1
=> use chocolateyguicli instead of chocolateygui for setting config values

Source/ChocolateyGui.Common.Windows/Controls/InternetImage.xaml.cs
=> (GH-739) Improving image quality and fixing issues with "ico" files

Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml, Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
=> (GH-688) Inline context search

Source/ChocolateyGui.Common.Windows/Resources/Controls.xaml, Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs, Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs, Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml, Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj, Source/ChocolateyGui.Common/Services/AllowedCommandsService.cs, Source/ChocolateyGui.Common/Services/IAllowedCommandsService.cs
This will allow us to control "what" commands are allowed within the Chocolatey GUI interface.
=> (GH-757) Introduce concept of Allowed Commands

Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj, Source/ChocolateyGui.Common.Windows/Controls/InternetImage.xaml.cs, Source/ChocolateyGui.Common.Windows/packages.config, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/packages.config
Also fix possible NullPointerException in ExtractImageFromStream. If a Svg could not be loaded the Picture property is null.
=> Update Svg.Skia and some SkiaSharp dependencies

Source/ChocolateyGui.Common.Windows/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui.Common.Windows/Views/SettingsView.xaml, Source/ChocolateyGui.Common/Properties/Resources.Designer.cs, Source/ChocolateyGui.Common/Properties/Resources.resx
For both Chocolatey GUI and Chocolatey. This will make it much easier
to find the setting that you are interested in changing. This has been
implemented by using an ICollectionView for each collection, and then
applying a filter method to each one, based on what is typed into the
search textbox.
Fixes #838
=> (#838) Add ability to filter features/settings

Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj, Source/ChocolateyGui.Common.Windows/Services/DialogService.cs, Source/ChocolateyGui.Common.Windows/Services/IDialogService.cs, Source/ChocolateyGui.Common.Windows/Services/IProgressService.cs, Source/ChocolateyGui.Common.Windows/Services/ProgressService.cs, Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs, Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs, Source/ChocolateyGui.Common.Windows/ViewModels/LocalSourceViewModel.cs, Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs, Source/ChocolateyGui.Common.Windows/ViewModels/SettingsViewModel.cs, Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml, Source/ChocolateyGui.Common.Windows/Views/SettingsView.xaml, Source/ChocolateyGui.Common.Windows/Views/ShellView.xaml.cs
Introduce DialogService and move related methods from ProgressService to it.
=> Introduce DialogService

.vscode/settings.json, ABOUT.md, CREDITS.md, README.md
This has been replaced by a Discord Server instead
Fixes #898
=> Remove mention of Gitter

Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
This PR fixes the broken progress dialog on all package operations.
Closes #875
=> (#875) Don't use ConfigureAwait(false) inside a progress dialog context

Source/ChocolateyGui.Common.Windows/ViewModels/ShellViewModel.cs
Fix keyboard bindings in conjunction with aggregated source view.
See connected issue #915 
In this scenario, ideally, the separator should be completely ignored.
Fixes #915
=> (#915) Fix keyboard bindings in conjunction with aggregated source view

.teamcity/settings.kts
Also removes unrequired imports that _aren't_ being used here.
Adds missing dependency to the build, and cleans up a few extra things that didn't need to be imported.
The build was failing to import.
1. Imported successfully on the internal dev server
ENGTASKS-331
=> (build) Adds Missing Dependency to Kotlin Build Definition

CREDITS.md, nuspec/chocolatey/ChocolateyGUI.nuspec, recipe.cake
- Updated CREDITS.md to include licensing information for our runtime dependencies.
- Updated nuspec to pull in CREDITS.md to a \legal\ folder.
- Moved LICENSE.txt to said \legal\ folder in the nupkg as it seemed appropriate
Moving this portion of the licensing doc we put together into this repo so that it can be kept up to date if/when dependencies change more easily.
- Run the Cake build and ensure that the generated package has a `legal` folder with the LICENSE.txt and CREDITS.md inside.
N/A
=> (maint) add/update 3rd party licenses information

.tx/config, recipe.cake
- Update Transifex config file to new format
- Replace usage of `transifex-client` with `transifex-cli` package\
- This has been submitted as a new package here: https://github.com/chocolatey-community/chocolatey-packages/pull/2164
- The public CI builds here will fail until that package has been accepted and pushed to CCR and approved
The older `transifex-client` is no longer supported and we are forced to use the new client which means changing the Choco package we use as it is a complete replacement for the old client and not necessarily a direct upgrade.
1. Run the build
2. Pull down the built package
3. Install it
4. Verify translations are incorporated correctly and changing languages in the application works as expected.
N/A
N/A
=> (maint) Update transifex usage in build

Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj, Source/ChocolateyGui.Common.Windows/packages.config, Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj, Source/ChocolateyGui.Common/packages.config, Source/ChocolateyGui/ChocolateyGui.csproj, Source/ChocolateyGui/packages.config, Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj, Source/ChocolateyGuiCli/packages.config
- Update LiteDB dependency
Necessary dep update.
1. Install and run the built version of gui
2. Ensure gui settings work, turn some things on and off, change languages...
No major changes here tbh (just a minor dep version bump), so given it builds and runs I'm happy. 😁 
Win11, Win10
Fixes #985
=> (#985) update liteDB dependency

.teamcity/settings.kts, recipe.cake
Update to latest Chocolatey.Cake.Recipe
Keeping repositories up to date with the version of Chocolatey.Cake.Recipe
- Ran `build.bat` locally
- Set a Team City build to run on this PR branch.
N/A
- ENGTASKS-3694
=> (build) (ENGTASKS-3694) Update Chocolatey.Cake.Recipe to latest

.vscode/extensions.json
Add recommend extension for VSCode
This extension is useful when editing Markdown files, especially when it contains a Table Of Contents. This extension will update the TOC simply by making changes to the main body.
N/A
N/A
N/A
=> (maint) Add recommended extension
