chocolatey/ChocolateyGUI

- Source/ChocolateyGui/Views/Controls/LocalSourceControl.xaml
- Source/ChocolateyGui/Views/Controls/RemoteSourceControl.xaml
- Source/ChocolateyGui/Views/Windows/MainWindow.xaml
I used a four-pixel margin to the controls, as I thought that looked good. In addition, I adjusted some of the thicknesses of the margins to not add extra padding where there already was some applied from the parent control. (This is why you see `Thickness="0,4,0,4"` in the below diff.) If you disagree on the amount of padding applied, please comment and I will revise my PR.
> (GH-285) Add Control Margins

- Source/ChocolateyGui/ViewModels/Controls/LocalSourceControlViewModel.cs
What this change do:
1. After finishing "Update all" the packages are reloaded and are filtered.
2. After "Update all" was cancelled the list is reloaded and filtered.
3. After "Refresh packages" the list is filtered.
Hope it knocks out all possibilities we have there.
> (GH-288) Filter packages list after refreshing or updating all packages.

- Source/ChocolateyGui/ViewModels/RemoteSourceViewModel.cs
The calculation of needed pages (PageCount) was wrong because of an invalid integer calculation where a floating-point operation would be needed.
Without this change there might be not enought pages to display all packages.
Example: 60 packages in repo - only 1 page containing 50 packages would be visible
> (GH-331) missing packages in ChocolateyGUI

- nuspec/chocolatey/ChocolateyGUI.nuspec
Update nuspec to be more compatible with [Core Team Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines):
* Update Icon to new logo and use commit hash
* Add `projectSourceUrl`
* Add `packageSourceUrl`
* Add `bugTrackerUrl`
* Update description as per [Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#123-informative-description)
* Add `foss` tag as per [Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#122-obligatory-tags)
Not done but might be a good idea:
* Change package id to lowercase
* Add logo to this repository to avoid linking to another repository
> Update to be compliant with core team guidelines

- Source/ChocolateyGui/Bootstrapper.cs
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Properties/Resources.Designer.cs
- Source/ChocolateyGui/Properties/Resources.resx
- Source/ChocolateyGui/Providers/ChocolateyCustomSchemeProvider.cs
- Source/ChocolateyGui/Providers/VersionNumberProvider.cs
- Source/ChocolateyGui/Resources/Controls.xaml
- Source/ChocolateyGui/Services/ChocolateyRemotePackageService.cs
- Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui/ViewModels/PackageViewModel.cs
- Source/ChocolateyGui/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui/ViewModels/SettingsViewModel.cs
- Source/ChocolateyGui/ViewModels/SourcesViewModel.cs
- Source/ChocolateyGui/Views/PackageView.xaml
- Source/ChocolateyGui/Views/SettingsView.xaml
A few text and header attributes in the xaml files was not moved to the Resource.resx file.
this PR fixes that.
It also changes ResXFileCodeGenerator to PublicResXFileCodeGenerator so that if new strings are added to the Resource.rex file or the designer is regenerated it will make the properties public (which is needed to be able to use them in xaml).
#405
> (GH-405) Moved hard coded text strings to resource file

- Source/ChocolateyGui/Services/ChocolateyRemotePackageService.cs
Currently Chocolatey GUI will attempt to acquire a static port, and simply fail if this port is already in use. This change has GUI check for an available port, and only fail if it can't find one open in an available range. 
(This was already already implemented in Subprocess, it was just never brought over to GUI side).
> (GH-372) Dynamically select open port for subprocess

- Source/ChocolateyGui.Subprocess/Program.cs
- Source/ChocolateyGui/Bootstrapper.cs
- docs/input/credits.md
Exposes a simple undocumented env var for setting ChocolateyGUI's log level at runtime. 
Eventually I'll be adding a user toggleable switch to settings.
Var: `CHOCOLATEYGUI__LOGLEVEL`
Levels (Case insensitive and correspond to interneral Serilog levels):
```
//
// Summary:
//     Anything and everything you might want to know about a running block of code.
Verbose,
//
// Summary:
//     Internal system events that aren't necessarily observable from the outside.
Debug,
//
// Summary:
//     The lifeblood of operational intelligence - things happen.
Information,
//
// Summary:
//     Service is degraded or endangered.
Warning,
//
// Summary:
//     Functionality is unavailable, invariants are broken or data is lost.
Error,
//
// Summary:
//     If you have a pager, it goes off when one of …
```
> Add log level switch.

- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Properties/Resources.nb.resx
This is not a complete translation (as well as some of the translated entries could definitely be improved)
The following have not been translated:
- LocalSourceViewModel (no need to translate)
- PackageVewModel_StartLoadingFormat (Same format can be used in norwegian)
- SettingsView_SubheaderChoco (no need to translate)
- SettingsView_ToggleElevateByDefault (don't know what the correct translation would be)
- SourcesView_Choco (no need to translate)
fixes #404
> (GH-404) Added Norwegian Bokmål translation

- Source/ChocolateyGui.Shared/ChocolateyGui.Shared.csproj
- Source/ChocolateyGui.Shared/Models/ChocolateySource.cs
- Source/ChocolateyGui.Shared/packages.config
- Source/ChocolateyGui.Subprocess/ChocolateyGui.Subprocess.csproj
- Source/ChocolateyGui.Subprocess/ChocolateyService.cs
- Source/ChocolateyGui.Subprocess/Program.cs
- Source/ChocolateyGui.Subprocess/packages.config
- Source/ChocolateyGui/Base/ConnectionClosedException.cs
- Source/ChocolateyGui/Bootstrapper.cs
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Elevation.cs
- Source/ChocolateyGui/Properties/Resources.Designer.cs
- Source/ChocolateyGui/Properties/Resources.de.resx
- Source/ChocolateyGui/Properties/Resources.resx
- Source/ChocolateyGui/Properties/Resources.sv.resx
- Source/ChocolateyGui/Resources/Controls.xaml
- Source/ChocolateyGui/Services/ChocolateyRemotePackageService.cs
- Source/ChocolateyGui/Services/IChocolateyPackageService.cs
- Source/ChocolateyGui/Startup/ChocolateyGuiModule.cs
- Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui/Views/PackageView.xaml
- Source/ChocolateyGui/Views/SettingsView.xaml
- Source/ChocolateyGui/packages.config
When using self-service installs, a feature in Chocolatey for Business,
it provides a background agent that actually performs the
installations. Chocolatey itself handles passing through the proper
information to the background service so that installations can occur.
The GUI should notice the feature is switched on and adjust to allow
non-administrators to run certain commands in the GUI without
attempting to elevate.
Supersedes #382
Closes #371
> (GH-371) Enable self-service mode

- Source/ChocolateyGui/Services/ChocolateyService.cs
- Source/ChocolateyGui/Services/IChocolateyService.cs
- Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui/Views/LocalSourceView.xaml
Makes the data grid for the Local Source package view single select. We don't support bulk operations (currently).
Replaces buggy filter and package update code with an ICollectionView which handles filtering, and improve package self-operation behavior.
Resolves #463, #462, #421.
Built on top of #466 changes.
> Make Local Grid Single Select and more intelligently filter Packages

- Source/ChocolateyGui/Views/SettingsView.xaml
Use `Grid.IsSharedSizeScope` and `SharedSizeGroup` for columns, so every language should now show it's labels.
Fixes #478
> (GH-478) Fix German texts in settings page are to long

- Source/ChocolateyGui/Properties/Resources.nb.resx
Added a few missing translations, as well as the ones mentioned in issue #486 
*Sorry about the incorrect whitespace, it was added by the [resxtranslator](https://github.com/HakanL/resxtranslator) tool (this will probably be added by transifex as well when translations are moved there)*
> Added missing translated strings for Norwegian Bokmål

- setup.cake
There was a thought that FileExists was robust enough to handle nulls
or empty strings and return false (because of course a null file
doesn't exist), but it appears that it simply does no validation and
allows the null value check against File.Exists, which errors on
missing paths. Check to be sure the value is empty prior to sending it
to the helper method.
> (build) Fix sign criteria for null paths

- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Utilities/Converters/NullToValue.cs
- Source/ChocolateyGui/Utilities/Converters/NullToVisibility.cs
- Source/ChocolateyGui/Views/PackageView.xaml
This PR fixes the empty space on the package view if there no package release notes given.
**Before**
**After**
Closes #501
> GH501: Fix Package description space

- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Models/ChocolateyGUISetting.cs
- Source/ChocolateyGui/Resources/ControlStyles/ToggleSwitch.xaml
- Source/ChocolateyGui/Resources/ControlStyles/Typography.xaml
- Source/ChocolateyGui/Utilities/BindingProxy.cs
- Source/ChocolateyGui/Views/SettingsView.xaml
This PR improves a little bit the UI for GUi and Feature Settings lists.
Todos after this PR:
- the GUI settings needs now also a title for the UI
- the GUI descriptions should be also be updated
**Before**
**After**
> UI Tweak for GUI and Feature Settings lists

- Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui/ViewModels/RemoteSourceViewModel.cs
- Due to the fact that ViewModel, which hasn't been initialized, isn't regsitered
to subscribe to SettingChanged event, therefore it didn't "see" the change
- Move default ListViewMode setting into the initialize event to work around
this.
> (GH-618) Correct issue with ListViewMode default

- .tx/config
A new language was added on transifex which uses the full language code, as such
this pr adds a transifex language mapping so the language code would be in the expected format for .NET.
Without this change, the language would be mapped as 'Resources.zh_CN.resx' and possibly make the program crash
> (maint) Added Chinese language map

- Source/ChocolateyGui/Services/ChocolateyService.cs
- Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs
Related to #626 #506 #585 
I reverted changes from #557 (calling .ToLower() on package.Id) and changed comparing Ids to case insensitive.
> (GH-506) Fix showing outdated packages

- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Resources/Controls.xaml
- Source/ChocolateyGui/ViewModels/SourceSeparatorViewModel.cs
- Source/ChocolateyGui/ViewModels/SourcesListBoxItemStyleSelector.cs
- Source/ChocolateyGui/ViewModels/SourcesViewModel.cs
- Source/ChocolateyGui/Views/SourcesView.xaml
This PR adds a `SourceSeparatorViewModel` class which can be used to show a separator between source items.
> (GH-646) Possibility for separators in the source lists

- Source/ChocolateyGui/Resources/Controls.xaml
- Source/ChocolateyGui/Views/PackageView.xaml
Sometimes the Release notes at the Package view seems like to be empty if there are only one line of text (e.g. #501).
To make this a little bit better I changed the UI to use Separator and increased Margins.
Closes #501
> (GH-501) Improve UI for Package view

- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/Resources/Controls.xaml
- Source/ChocolateyGui/Utilities/BubbleScrollEventBehavior.cs
- Source/ChocolateyGui/Views/PackageView.xaml
The rendering of headings in description are larger then the headings of the Package view.
To improve the Package view the headings outside of the description have now the same font size and weight. Also the Icon and the Id are moved to the left side. The right side is now vertically stretched and can be scrolled if it's to large.
Closes #356
> (GH-356) Improve Package view

- Source/ChocolateyGui/Controls/InternetImage.xaml.cs
Keep aspect ratio for Icons in Tile and Package view.
Also make the download of the icons faster by using a memory stream instead a temporary file stream.
**Before**
**After**
Closes #633 
/cc @gep13 @mwallner @ferventcoder @pascalberger
> (GH-633) Keep aspect ratio for Icons in Tile and Package view

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Commands/RelayCommand.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/ShellViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/ShellView.xaml
Fix 513 by adding keyboard bindings ctrl+1..9 to switch between respective source indexes.
Closes #513
> (GH-513) Add keybinding for navigating sources

- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
When a label is red, something wrong is implied, switching to DarkOrange
Implies a warning.
Merging this fixes #711
> (GH-711) prelease label should not be red

- .tx/config
Adds a mapping for the Czech language code
so it would be in the correct format for .NET
> Add Czech language map

- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common/Models/AppConfiguration.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
Add a toggle in the settings view to prevent a blank search when viewing
the list of available packages.
https://github.com/chocolatey/ChocolateyGUI/issues/706
> (GH-706) Add a settings to prevent searchs preloading

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Controls/Dialogs/ChocolateyDialog.xaml
- Source/ChocolateyGui.Common.Windows/Utilities/Converters/NullToBool.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
Add a ListView template to show a message when no matching packages were found.
Closes #742
> Show message at remote source view when no packages were found by search input

- nuspec/chocolatey/ChocolateyGUI.nuspec
- nuspec/chocolatey/chocolateyInstall.ps1
- nuspec/chocolatey/helper.ps1
I also switched to an helper.ps1 file for the package parameters to not
go over the 100 lines guideline.
Also the Package Parameter for UseDelayedSearch will now contain the
correct value.
Fixes #741  #749
> (GH-741 GH-749) Add missing package parameters

- Source/ChocolateyGui.Common.Windows/Resources/Controls.xaml
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
Reorder local and remote context menu and bring back menu icons.
Closes #745
> (GH-745) Reorder local and remote context menu and bring back menu icons

- nuspec/chocolatey/ChocolateyGUI.nuspec
In #741 I added a helper.ps1 file. This file was never added to the Chocolatey package.
Merging this fixes that.
Fixes #754
> (GH-754) Add missing helper.ps1 file to nuspec file

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/packages.config
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/packages.config
With this version I can fix an exception which I got at the `ChocolateyService` with the old one.
```csharp
private static Package GetMappedPackage(GetChocolatey choco, PackageResult package, IMapper mapper, bool forceInstalled = false)
{
var mappedPackage = package == null ? null : mapper.Map<Package>(package.Package);
if (mappedPackage != null)
```
System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
v7.0.1 is also the latest possible version for .Net v4.5.2
> Update Automapper to v7.0.1

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Controls/InternetImage.xaml.cs
- Source/ChocolateyGui.Common.Windows/app.config
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/app.config
- Source/ChocolateyGui/packages.config
Using this awesome [Svg.Skia](https://github.com/wieslawsoltes/Svg.Skia) to render Svg icons correctly.
Closes #756
> (GH-756) Improve Svg icon rendering by using Svg.Skia (SkiaSharp)

- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
- Source/ChocolateyGui.Common/Models/AppConfiguration.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
- Source/ChocolateyGui.Common/Services/IChocolateyService.cs
- nuspec/chocolatey/ChocolateyGUI.nuspec
- nuspec/chocolatey/helper.ps1
> (GH-769) Prevent automatic outdated package check

- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
Use different method names to prevent such a mistake in the future.
Closes #775
> (GH-775) Fix search at remote source

- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- docs/input/docs/business_features/index.cshtml
- docs/input/docs/commands/index.cshtml
- docs/input/docs/configuration/index.cshtml
- docs/input/docs/installation/chocolatey_gui.md
- docs/input/docs/localization.md
- docs/input/docs/uninstallation/chocolatey_gui.md
- docs/input/docs/uninstallation/chocolatey_gui_extension.md
- docs/input/docs/uninstallation/index.cshtml
- docs/input/docs/user_interface/index.cshtml
When setting up the RemoteSourceViewModel, the DefaultToTileViewForLocalSource was
being used, where the DefaultToTileViewForRemoteSource used be getting used instead.
Fixes #782
> (GH-782) Ensure correct property is used

- README.md
https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1536?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDExNTg2MDQ4MzU6MTY0MTgxOTc%3D#issuecomment-694702815
> Add link to wixtoolset Visual Studio integration 

- Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
- Source/ChocolateyGui.Common.Windows/Controls/InternetImage.xaml.cs
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/SettingsViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/ShellViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/SourcesViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/ShellView.xaml.cs
- Source/ChocolateyGui.Common/Commands/ConfigCommand.cs
- Source/ChocolateyGui.Common/Commands/FeatureCommand.cs
- Source/ChocolateyGui.Common/Models/AppConfiguration.cs
- Source/ChocolateyGui.Common/Models/ChocolateyGuiConfiguration.cs
- Source/ChocolateyGui.Common/Models/InformationCommandConfiguration.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
- Source/ChocolateyGui.Common/Services/ConfigService.cs
- Source/ChocolateyGui.Common/Services/IConfigService.cs
- Source/ChocolateyGui.Install/Product.wxs
- Source/ChocolateyGuiCli/Bootstrapper.cs
- Source/ChocolateyGuiCli/Program.cs
- Source/ChocolateyGuiCli/Startup/ChocolateyGuiCliModule.cs
Very early days, but things seem to be working....
Relates to #602
> (GH-602) Initial attempt at getting things working

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Resources/Controls.xaml
- Source/ChocolateyGui.Common.Windows/Utilities/ToolTipBehavior.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/LocalSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
The decision was taken to allow a button to be enabled/disabled based on
current Chocolatey configuration (mainly when running in background
service mode). To allow for this, whilst still allowing a button to be
enabled/disabled based on application logic, a new behavior was
introduced to encapsulate this logic.
This will allow the Chocolatey GUI Licensed Extension to override the
AllowedCommandsService, to control which operations should be enabled
and disabled, based on the background service configuration.
Relates to #757
> (#757) Allow buttons to be enabled/disabled

- Source/ChocolateyGui.Common.Windows/ViewModels/LocalSourceViewModel.cs
The IsShowOnlyPackagesWithUpdateEnabled will be false if the PreventAutomatedOutdatedPackagesCheck is not set. So you will not see any updated packages without forcing the search for it.
This PR fix this issue.
Closes #821
> Fix logic of IsShowOnlyPackagesWithUpdateEnabled when PreventAutomatedOutdatedPackages is not set

- Source/ChocolateyGui.Common.Windows/Services/IProgressService.cs
- Source/ChocolateyGui.Common.Windows/Services/ProgressService.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
A confirmation dialog is being added to the reinstall and uninstall
operations since these can be harmful operations to the system.
Fixes #786
> (#786) Add confirmation for destructive operations

- Source/ChocolateyGui.Install/ChocolateyGui.Install.wixproj
- Source/ChocolateyGui.Install/NetFx48.wxs
- Source/ChocolateyGui.Install/Product.wxs
in the installer.
While the code I used to implement the check is part of multiple comments/discussions I decided to copy from the "original", so I added an extra comment for the license of the original (MS-RL).
The whole file `NetFx48.wsx` can be removed, once the Wix version is bumped to one greater than v3.14.0.4118.
fixes #842
> (#842) added a check for NET Framework 4.8

- CONTRIBUTING.md
Dead and inactive links updated to help new devs sign the agreement and 
communicate about issues. Git commands added and some sentences 
reworded for clarity.
Issue #854
> (#854) Update to contributing.md 

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/Startup/AssemblyResolver.cs
- Source/ChocolateyGui/App.xaml.cs
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGuiCli/Bootstrapper.cs
- Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj
- Source/ChocolateyGuiCli/Program.cs
- Source/ChocolateyGuiCli/Runner.cs
This pull request updates the Chocolatey GUI and Chocolatey GUI CLI Assembly Loader to load the main Chocolatey executable as an assembly, instead of loading the included Chocolatey DLL file.
With the changes made here, the DLL file will no longer be included in the installation.
fixes #857
> (#857) Load Chocolatey executable assembly

- Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Services/DialogService.cs
- Source/ChocolateyGui.Common.Windows/Utilities/ChocolateyMessageBox.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/ShellView.xaml.cs
- Source/ChocolateyGui/App.xaml.cs
There appears to be a "feature" in WPF that prevents MessageBoxes from
displaying when there are no active windows. Many of our MessageBoxes
are to report errors, and many of them occur during startup. This
results in them not displaying as we haven't created any windows. This
works around that by creating a hidden window and closing it after the
MessageBox has been displayed.
Wrap message boxes with calls to display a hidden window.
There is apparently a "feature" of WPF that prevents message boxes from displaying unless there's a window being displayed.
Caveat: I have not verified that all 7 message boxes are displayed, merely the one that I was able to reliably reproduce. I also did not verify the overloads that don't have any references (yet). I merely added them so we have them if …
> (#904) Wrap MessageBoxes with a hidden window

- Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs
- Source/ChocolateyGuiCli/Startup/ChocolateyGuiCliModule.cs
This commit makes changes to how the Chocolatey API is being called,
which then allows the original logging that Chocolatey implements
to still happen when we add our own Serilog logger.
This change depends on a new change in the Chocolatey codebase,
and a new release of the program.
fixes #697
Heavily dependent on Chocolatey PR https://github.com/chocolatey/choco/pull/2295
Do Not Merge until a new release of Chocolatey with the PR mentioned is released.
> (#697) Update Chocolatey API calling

- Source/ChocolateyGui.Common.Windows/Services/PackageArgumentsService.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
- Source/ChocolateyGui.Common/Models/AppConfiguration.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
This pull request updates the code that was added previously for displaying package arguments with code to hide sensitive arguments, only do a log if the arguments file can not be found, display a message about no arguments could not be found if nothing is returned and to hide the button for viewing package arguments when the package is not installed.
The sensitive arguments are changed to not be displayed, as we do not want to dispay these arguments to the users in the possibility that they are not the same user as the one that installed the package.
Changing to logging of the file not found was to prevent duplicated dialogs to be shown, but still give the information about no arguments being available.
Additionally, there is no reason to be able to view package arguments for packages …
> (#770) Provide ability to see persisted arguments for installed package

- .teamcity/pom.xml
- .teamcity/settings.kts
This commit adds a build definition to be used by the Chocolatey
internal TeamCity server.
This calls the build.official.bat script, as it will have access to the
required files in order to create an official signed version of
Chocolatey GUI.
Setup of this build uses the build of Chocolatey GUI Licensed Extension
as a template, and then modified the necessary portions to make it
specific to Chocolatey GUI.
All Chocolatey builds are going to happen on an internal TeamCity server, to allow for full signing of the generated assemblies.
The TeamCity build configuration has been tested on a previous TeamCity server, and brought over in the settings.kts file.
N/A
> (build) Adds TeamCity build definition

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/packages.config
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/packages.config
- Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj
- Source/ChocolateyGuiCli/packages.config
- nuspec/chocolatey/ChocolateyGUI.nuspec
This commit updates the the dependency for Chocolatey CLI
to the latest pre-release we have available internally.
This will prevent temporarily users from building the project
until a new release is made.
Additionally a pre-release version range is added to the nuspec
file to allow us to test upcoming functionality in the way we
want.
To allow us to test the functionality and installation we intend for upcoming releases.
N/A
Related #928  
https://app.clickup.com/t/20540031/ENGTASKS-1149
> (#928) Update Chocolatey CLI to latest pre-release

- recipe.cake
This commit updates the cake build script to add
the sources we need to use explicitly, with the
ability to add a nuget source from an environment
variable when it is present.
This is needed due to a temporary change to use
versions of Chocolatey CLI that are only available
on our internal feed currently.
1. Tested by running build.ps1
https://app.clickup.com/t/20540031/ENGTASKS-1149
> (maint) Add sources explicitly during cake build

- CONTRIBUTING.md
- Update-DebugConfiguration.ps1
Add debugging information to contributing document and provide a script to help with the process.
Because Chocolatey GUI depends on the system installed Chocolatey, the Chocolatey.Lib package needs to be the same version that is installed. This isn't currently called out in the contributing documentation, nor do we provide an easy way to update.
I have used the provided script several times to update the Chocolatey.Lib version targeted while working on the 1.1.0 release.
Fixes #902
> (#902) Add debug info to Contributing document

- CONTRIBUTING.md
- Tests/chocolateyguicli.Tests.ps1
- Tests/helpers/gui-helpers.psm1
- Tests/helpers/gui/Get-GuiFeature.ps1
- Tests/helpers/gui/Invoke-GuiCli.ps1
Add some initial Pester tests.
There is some very basic tests of `chocolateyguicli` that we do as part of manual testing before a release. This puts those into Pester tests so we don't have to manually do them.
On a system with Chocolatey GUI installed:
1. Run: `Install-Module Pester -MinimumVersion 5.3.1 -SkipPublisherCheck -Force -Scope CurrentUser`
2. From the `Tests` directory run `Invoke-Pester`
3. Confirmed all tests returned successfully.
Fixes #956
> (#956) Add initial set of Pester tests

- README.md
- recipe.cake
Update to allow building with Visual Studio 2022 alone.
We no longer need to hard code the required Visual Studio version as the chocolatey cake recipe has been updated.
On a system with only Visual Studio 2022 installed ran the build script. Confirmed Chocolatey GUI built as expected.
This is not a code change, but the OS used to build was Windows 10 22H2.
N/A
> (build) Allow building with Visual Studio 2022

- GitVersion.yml
- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/AdvancedInstallViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/RemoteSourceViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/Models/Messages/PackageChangedMessage.cs
- Source/ChocolateyGui.Common/Models/Messages/PackageHasUpdateMessage.cs
- Source/ChocolateyGui.Common/Models/NuGetVersionTypeConverter.cs
- Source/ChocolateyGui.Common/Models/OutdatedPackage.cs
- Source/ChocolateyGui.Common/Models/Package.cs
- Source/ChocolateyGui.Common/Services/IChocolateyService.cs
- Source/ChocolateyGui.Common/ViewModels/Items/IPackageViewModel.cs
- Source/ChocolateyGui.Common/packages.config
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/packages.config
- Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj
- Source/ChocolateyGuiCli/packages.config
Update `chocolatey.lib` to a build using the new NuGet assemblies. 
Changes various items to adjust to breaking API changes in the new library version. Specifically `SemanticVersion` was replaced with `NuGetVersion`, and changes to adjust for the move from `IPackage` to `IPackageMetadata` and `IPackageSearchMetadata` were the main things required.
ChocolateyGUI will need to work with Chocolatey v2.0.0
- Opened ChocolateyGUI
- Went to CCR feed and looked at default page (paging and ordering known broken)
- Searched on CCR feed
- Viewed details of a package.
- Added local feed with outdated wget package available
- Viewed local feed
- Installed wget from that local feed
- Noted that wget was correctly marked as outdated
- Updated wget from CCR
- Pinned and unpinned wget
- Viewed details for …
> (#974) Preliminary update chocolatey.lib

- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/AdvancedInstallViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/AdvancedInstallView.xaml
- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/Models/AdvancedInstall.cs
- Source/ChocolateyGui.Common/Models/Package.cs
- Source/ChocolateyGui.Common/Properties/Resources.Designer.cs
- Source/ChocolateyGui.Common/Properties/Resources.resx
- Source/ChocolateyGui.Common/ViewModels/Items/IPackageViewModel.cs
- Source/ChocolateyGui.Common/packages.config
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/packages.config
- Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj
- Source/ChocolateyGuiCli/packages.config
- Remove usage of side by side related properties that have been removed upstream
- Switch to new default for `choco list`
Removing deprecated features.
1. Compiled the solution
2. Opened Chocolatey GUI 
3. Checked to make sure installed packages are shown correctly
4. Checked to make sure that remote packages are returned from remote feed
Win10
Fixes #990 and #989
> (#990 #989) Update to latest chocolatey bits

- Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/Services/PackageArgumentsService.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/AdvancedInstallViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/ShellView.xaml.cs
- Source/ChocolateyGui.Common/Commands/ConfigCommand.cs
- Source/ChocolateyGui.Common/Commands/FeatureCommand.cs
- Source/ChocolateyGui.Common/Commands/GenericRunner.cs
- Source/ChocolateyGui.Common/Models/AppConfiguration.cs
- Source/ChocolateyGui.Common/Providers/ChocolateyConfigurationProvider.cs
- Source/ChocolateyGui.Common/Services/ChocolateyGuiCacheService.cs
- Source/ChocolateyGui.Common/Services/ConfigService.cs
- Source/ChocolateyGui.Common/Startup/AutoFacConfiguration.cs
When the ability to show remembered arguments in Chocolatey GUI was
first introduced, code from the set_package_config_for_upgrade (which
was renamed to SetConfigFromRememberedArguments) method was borrowed,
as it was doing very similar work.  However, the code that was brought
over to Chocolatey GUI failed to realise that after splitting the
arguments on " --", when passed into the
arguments_contain_sensitive_information (which was renamed to
SensitiveArgumentsProvided) that a sensitive variable would no longer
be detected as this method expects that all arguments under test start
with a "-".
Ensure that no sensitive persisted arguments are displayed through Chocolatey GUI.
1. Enable the Chocolatey feature to use remembered arguments
1. Install a package using Chocolatey CLI where a …
> (#1000) Do not display sensitive persisted package arguments

- .editorconfig
- Source/ChocolateyGui.Common.Windows/ChocolateyGui.Common.Windows.csproj
- Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
- Source/ChocolateyGui.Common.Windows/Utilities/Converters/NuGetVersionToString.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/AdvancedInstallViewModel.cs
- Source/ChocolateyGui.Common.Windows/ViewModels/Items/PackageViewModel.cs
- Source/ChocolateyGui.Common.Windows/Views/LocalSourceView.xaml
- Source/ChocolateyGui.Common.Windows/Views/PackageView.xaml
- Source/ChocolateyGui.Common.Windows/Views/RemoteSourceView.xaml
- Source/ChocolateyGui.Common.Windows/packages.config
- Source/ChocolateyGui.Common/ChocolateyGui.Common.csproj
- Source/ChocolateyGui.Common/packages.config
- Source/ChocolateyGui/BannedSymbols.txt
- Source/ChocolateyGui/ChocolateyGui.csproj
- Source/ChocolateyGui/packages.config
- Source/ChocolateyGuiCli/ChocolateyGuiCli.csproj
- Source/ChocolateyGuiCli/packages.config
This pull request normalizes the dispaying and usages of normalized version numbers.
To aid and try prevent non-normalized version numbers used, a banned API analyzer has also been added.
We should use the equivalent of version normalization that was introduced in Chocolatey CLI v2.0.0.
1. Open Chocolatey GUI
2. Navigate to the Chocolatey Source
3. Search for 7zip.portable
4. Verify 7zip.portable is shown with normalized version (ie 3 part version without leading zeros).
5. Open detail page.
6. Verify again only normalized version numbers are shown.
7. Click button for advanced installation.
8. Verify drop down list shows normalized version number of latest version.
9. Install the package.
10. Navigate to `This PC`.
11. Verify installed 7zip.portable package is shown with normalized …
> (#1005) Normalize version numbers

- Source/ChocolateyGui.Common.Windows/Utilities/Converters/NuGetVersionToString.cs
- Source/ChocolateyGui.Common/Providers/ChocolateyConfigurationProvider.cs
This sets the Chocolatey install directory to the current assembly directory when built as a debug build. 
If a debug build is in use, then Chocolatey GUI is using the chocolatey lib assembly, so true can be returned in all cases.
This allows correctly getting the location of remembered arguments from the debug installed package(s) instead of from the system-wide install of Chocolatey.
1. Build a debug version of Chocolatey GUI
1. F5 run from Visual Studio
1. Advanced install curl with package parameter(s)
1. View the remembered arguments.
1. Validate that they are coming from the local/debug install of curl, rather than from the system wide install.
- Windows 10 22H2
Fixes #980
> (#980) When using debug install, use assembly directory for install location

- .teamcity/settings.kts
NOTE: This PR should not be merged until Chocolatey CLI v2.0.0 has been released. This repo also currently does not differentiate between unit and integration tests (if I'm reading things correctly), so merging may need to wait until that is the case.
This PR adds a schedule trigger to the TeamCity build, and also adjust the build so that it selects which tests to run based on how the build was triggered.
It also adjusts the GitHub workflow for pushes and pull requests to only run unit tests.
Integration tests take a long time to run, and do not need to be run on every commit. Reducing the tests run on each commit to only unit tests will speed up the feedback loop.
Running full integration tests on a schedule means that we still benefit from the coverage they give without slowing down the …
> (#993) (ENGTASKS-2347) Run integration tests only on scheduled builds

- .teamcity/settings.kts
- build.bat
- build.debug.bat
- build.official.bat
This PR removes the duplicate assignment of scriptContent in the Call Cake script step.
The syntax was incorrect and prevented the KTS file from being imported.
I compared this file pre and post edit to the other KTS files that are importing, was also guided by the error messages from the failed import.
N/A
Related to #993
> (#993) (fix) Correct syntax in KTS file, duplicate scriptContent assignment

- Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
- Source/ChocolateyGuiCli/Bootstrapper.cs
This commit introduces a change similar to what exists in Chocolatey CLI.  While in debug mode, we source the installation location of both Chocolatey and the GUI Licensed assembly from a different location, rather than the official location.
This means that we can run the debug version of Chocolatey GUI using a locally sourced debug version of Chocolatey, which means that debugging some scenarios is much easier.
This PR should be tested alongside a PR into Chocolatey GUI Licensed, which makes use of this change.
N/A
N/A - This is merely for allowing better development experience when working with Chocolatey GUI
> (maint) Allow better debugging of Chocolatey GUI

- .github/workflows/build.yml
- .teamcity/settings.kts
- recipe.cake
This PR splits the current general TeamCity build which runs unit tests on a version control trigger and unit + integration tests on a schedule into two separate builds:
* Chocolatey GUI (Built with Unit Tests) `ID: ChocolateyGUI`
* Chocolatey GUI (Scheduled Integration Testing) `ID: ChocolateyGUISchd `
It also introduces an additional build specifically for running Code Analysis and Dependency Checking:
* Chocolatey GUI (SonarQube) `ID: ChocolateyGUIQA`
Note: Please advise if these names are appropriate and recommend alternatives as needed.
This change enables TeamCity to accurately track how long each build configuration should take to run and how many tests each should run.
This has been tested on a non-Production TeamCity instance, the KTS file imported successfully and the three …
>  (ENGTASKS-3098) Create TC build for Unit, Integration, and QA

- .teamcity/settings.kts
This PR installs the `dotnet-6.0-runtime` package required for the QA Build / Dependency-Check to run.
Older versions of the build agent had this baked in, but it is no longer in newer versions. Instead of re-introducing it to the build agent image, we'll install it when needed in order to run the Dependency-Check task.
To test that the build agents can install `dotnet-6.0-runtime` and that installing it allows the Dependency-Check task to run, the user data script was temporarily amended to add this install at that point in the build process.
This worked and the Dependency-Check task ran as expected.
- Windows Server 2019
Build
N/A
> (build) Install dotnet-6.0-runtime for QA Build

- Source/ChocolateyGui.Common.Windows/Startup/ChocolateyGuiModule.cs
- Source/ChocolateyGui.Common/Hacks.cs
- Source/ChocolateyGuiCli/Startup/ChocolateyGuiCliModule.cs
Create the `C:\ProgramData\Chocolatey GUI\Config\` directory if it doesn't already exist.
LiteDatabase doesn't handle creating the directory if it's not there. And cannot create it's file if the parent directory doesn't exist.
1. Delete `C:\ProgramData\Chocolatey Gui\` directory.
2. Launch Chocolatey GUI.
3. Ensure it doesn't error.
4. Delete `C:\ProgramData\Chocolatey Gui\` directory.
5. Run `chocolateyguicli -?`.
6. Ensure Help is output by Chocolatey GUI CLI.
- Windows 10
- Windows 11
Fixes #996
> (#996) Create config directory if it doesn't exist

- .teamcity/settings.kts
This PR makes each build configuration in the TeamCity KTS file reference a template containing standard Slack notification configuration, which applies said configuration to the build configuration without having to duplicate it in each.
Enables standard notification configuration across all build configurations in this project.
This change was initially tested by pointing a development TeamCity instance at the equivalent changes on the `chocolatey/choco` project. These notification changes are now live for that project and have been operating in production for some time.
N/A
Build configuration change (non-breaking)
~~* [ ] Bug fix (non-breaking change).~~
~~* [ ] Feature / Enhancement (non-breaking change).~~
~~* [ ] Breaking change (fix or feature that could cause existing …
> (build) Add templated notifications to all build configurations
